title: Webpage Customisation
description: This page introduces the basics on how to customise your very own website!
show_downloads: true

baseurl:  # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://dfslimjr.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
This page was last updated at {{ "now" | date: "%2022-%04-%03 %1:%00" }}.
theme: # leave it empty

# social
author: SAYES
image: /thumbnail-jumbo.png
twitter:
  username: SAYES

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
